[build]
  functions = "./functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
